### ISSUE TITLE
Cannot load module HomeConnectConnection

### ISSUE THREAD

**Issue by MiguelESP89** [sw-home/FHEM-HomeConnect#1]
Hey, 
vielleicht kann mir jemand helfen. Ich habe die Anleitung durchgeführt und bekomme immer beim 
ausführen von 
define hcconn HomeConnectConnection xxx http://xxx:8083/fhem?cmd.Test=set%20hcconn%20auth%20&fwcsrf=xxx simulator

die Fehlermeldung 
Cannot load module HomeConnectConnection

Ich kann mir leider nicht erklären wieso und weshalb. 

Liebe Grüße
Miguel

**Comment by docb7** [comment]
Servus, hatte ich auch - irgendwie wurde zwar Benutzer und Gruppe richtig übernommen aber nicht die Rechte. Versuch mal:
sudo chmod 775 48_HomeConnectConnection.pm
sudo chmod 775 48_HomeConnectConnect.pm

Ach und das hier nicht vergessen (falls nicht schon erledigt): sudo apt install libswitch-perl


Viele Grüße
