### ISSUE TITLE
time-"Error" in controls_homeconnect.txt

### ISSUE THREAD

**Issue by SmilyHM** [sw-home/FHEM-HomeConnect#3]
Hi,

habe gerade gesehen, dass sich das FHEM-Log ab und an beschwert ;-)

In der Datei controls_homeconnect.txt ist ein Zahlendreher oder einfach nur vertippt (Uhrzeit):

UPD 2018-08-22_11:09:**_90_** 31134 FHEM/48_HomeConnect.pm

Viele Grüße
Sascha

**Comment by sw-home** [comment]
Danke für den Hinweis! Ist gefixt
