### ISSUE TITLE
Dateigrößenangabe in controls_homeconnect.txt

### ISSUE THREAD

**Issue by SmilyHM** [sw-home/FHEM-HomeConnect#5]
Hi,

die Angabe der Dateigröße der 48_HomeConnect.pm ist in der controls_homeconnect.txt noch auf dem alten Stand --> muss noch von 31853 auf 30881 reduziert werden.

Viele Grüße
Sascha

**Comment by sw-home** [comment]
Sorry, ist mir ein Rätsel wie das passieren konnte, bei mir hat die Datei diese Größe die ich mit Commit 055eb70 aktualisiert hatte.

![grafik](https://user-images.githubusercontent.com/23035753/83725875-f499e480-a642-11ea-8bcb-2776abedc3ed.png)

**Comment by sw-home** [comment]
fixed in 1989db0
