### ISSUE TITLE
Updating HomeConnect in fhem not working

### ISSUE THREAD

**Issue by lutzbellmann** [sw-home/FHEM-HomeConnect#7]
Hi, thanks so much for this useful module!
Yet I found one issue: FHEM cannot load/update the module using the TXT file. This is obviously due to incorrect size in the TXT file.
See the FHEM log:
2021.11.24 21:18:08 1 : Downloading https://raw.githubusercontent.com/sw-home/FHEM-HomeConnect/master/controls_homeconnect.txt
2021.11.24 21:18:08 1 : 
2021.11.24 21:18:08 1 : homeconnect
2021.11.24 21:18:08 1 : UPD FHEM/48_HomeConnect.pm
2021.11.24 21:18:08 1 : Got 31752 bytes for FHEM/48_HomeConnect.pm, expected 30881
2021.11.24 21:18:08 1 : aborting.

-----------
Can this be corrected, please?

Thanks and regards,
Lutz

**Comment by sigma415** [comment]
Same problem here (also problem is already described in FHEM wiki)
Please update txt file.
Thank you.

**Comment by sw-home** [comment]
Both file sizes are updated
